const fs = require("fs");
const path = require("path");
const { roleDbEnv } = require("./scripts/db-role-env.cjs");

const DB_ROLE_BY_PROCESS = Object.freeze({
  "tz-web-v2": "TM_DATABASE_URL_WEB_COMMAND",
  "tz-dxy-synthetic": "TM_DATABASE_URL_ENGINE",
  "tz-expire-pending-orders": "TM_DATABASE_URL_EXECUTION",
  "tz-cleanup-rejection-log": "TM_DATABASE_URL_MAINTENANCE",
  "tz-ingestion": "TM_DATABASE_URL_INGEST",
  "tz-refresh-lifecycle": "TM_DATABASE_URL_LIFECYCLE",
  "tz-shadow-run": "TM_DATABASE_URL_BACKTEST",
  "tz-feature-freshness": "TM_DATABASE_URL_MONITOR",
  "tz-feature-freshness-healer": "TM_DATABASE_URL_ENGINE",
  "tz-db-session-inventory": "TM_DATABASE_URL_MONITOR",
});

// Load root .env files into process.env so PM2 apps get secrets even when the
// PM2 daemon was started from a shell that did not export them.
function loadEnvFile(name) {
  const file = path.join(__dirname, name);
  if (!fs.existsSync(file)) return;
  const lines = fs.readFileSync(file, "utf8").split(/\r?\n/);
  for (const line of lines) {
    const m = line.match(/^([A-Za-z0-9_]+)\s*=\s*(.*)$/);
    if (!m) continue;
    const key = m[1];
    let value = m[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (process.env[key] === undefined && value.length > 0) {
      process.env[key] = value;
    }
  }
}
loadEnvFile(".env.local");
loadEnvFile(".env.production.local");

const config = {
  apps: [
    {
      name: 'tz-web-v2',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3003',
      cwd: 'C:\\tradzfx-v2\\apps\\web',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: '3003',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-web',
        TM_DB_POOL_MAX: '20',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        TM_DB_STATEMENT_TIMEOUT: '60000',
        TM_MT5_API_KEY: process.env.TM_MT5_API_KEY,
        INTERNAL_TRIGGER_API_KEY: process.env.INTERNAL_TRIGGER_API_KEY,
        MT5_SYMBOLS: 'EURUSD,GBPUSD,USDJPY,USDCHF,USDCAD,USDSEK,AUDUSD,NZDUSD,XAUUSD',
        EMA_CROSS_PAIRS: '9/21,50/200',
        TM_DISABLE_FEATURE_JOBS: 'true',
        NINJA_LIVE_ENABLED: 'false',
        NINJA_LIVE_MODE: 'paper',
        NINJA_SYMBOLS: 'XAUUSD',
        NINJA_LOT_SIZE: '0.01',
        // Small-account safety guard: cap any risk-based lot calculation at 1 lot
        // and allow only one concurrent position total (and one per symbol).
        MAX_LOT_PER_ORDER: '1.0',
        SMALL_ACCOUNT_MAX_TOTAL: '5',
        SMALL_ACCOUNT_MAX_PER_SYMBOL: '1',
        SMALL_ACCOUNT_COOLDOWN_MINUTES: '30',
        SMALL_ACCOUNT_MAX_DAILY_LOSS_PCT: '5',
        SMALL_ACCOUNT_MAX_DAILY_LOSS_USD: '20',
        NODE_OPTIONS: '--max-old-space-size=4096',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-web-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-web-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-web-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '5000M',
      kill_timeout: 5000,
      listen_timeout: 3000,
      shutdown_with_message: true,
      watch: false,
    },
    // NOTE: tm-web-v2-ninja-trail removed because scripts/run-ninja-trail-cron.ts
    // does not exist and PM2 on Windows cannot execute node_modules/.bin/tsx.cmd.
    // Re-add as a compiled JS entry if the cron is revived.
    {
      name: 'tz-dxy-synthetic',
      script: 'C:\\tradzfx-v2\\scripts\\run-dxy-synthetic-cron.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-dxy-synthetic',
        TM_DB_POOL_MAX: '2',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-dxy-synthetic-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-dxy-synthetic-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-dxy-synthetic-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-expire-pending-orders',
      script: 'C:\\tradzfx-v2\\scripts\\expire-pending-orders-cron.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-expire-orders',
        TM_DB_POOL_MAX: '2',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        EXPIRE_PENDING_ORDERS_INTERVAL_MS: '30000',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-expire-pending-orders-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-expire-pending-orders-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-expire-pending-orders-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-cleanup-rejection-log',
      script: 'C:\\tradzfx-v2\\scripts\\cleanup-rejection-log-cron.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-cleanup-rejections',
        TM_DB_POOL_MAX: '2',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        CLEANUP_REJECTION_LOG_INTERVAL_MS: '3600000',
        REJECTION_LOG_RETENTION_DAYS: '7',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-cleanup-rejection-log-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-cleanup-rejection-log-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-cleanup-rejection-log-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-ingestion',
      script: 'C:\\tradzfx-v2\\scripts\\ingestion-server.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        INGESTION_PORT: '3004',
        NEXT_APP_URL: 'http://127.0.0.1:3003',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-ingestion',
        TM_DB_POOL_MAX: '10',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        TM_DB_STATEMENT_TIMEOUT: '30000',
        INGESTION_FORWARD_TRIGGER: 'true',
        INTERNAL_TRIGGER_API_KEY: process.env.INTERNAL_TRIGGER_API_KEY,
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-ingestion-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-ingestion-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-ingestion-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      listen_timeout: 3000,
      shutdown_with_message: true,
      watch: false,
    },
    {
      name: 'tz-refresh-lifecycle',
      script: 'C:\\tradzfx-v2\\scripts\\refresh-lifecycle-cron.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-lifecycle',
        TM_DB_POOL_MAX: '5',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        REFRESH_LIFECYCLE_INTERVAL_MS: '3600000',
        REFRESH_LIFECYCLE_LOOKBACK_DAYS: '2',
        REFRESH_LIFECYCLE_LIMIT: '5000',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-refresh-lifecycle-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-refresh-lifecycle-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-refresh-lifecycle-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-shadow-run',
      script: 'C:\\tradzfx-v2\\scripts\\shadow-run-cron.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-shadow-run',
        TM_DB_POOL_MAX: '5',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        SHADOW_RUN_INTERVAL_MS: '3600000',
        SHADOW_RUN_INTRABAR: 'sl_first',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-shadow-run-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-shadow-run-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-shadow-run-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-feature-freshness',
      script: 'C:\\tradzfx-v2\\scripts\\feature-freshness-monitor.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-feature-freshness',
        TM_DB_POOL_MAX: '3',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        EMA_CROSS_PAIRS: '9/21,50/200',
        SMA_CROSS_PAIRS: '50/200',
        FRESHNESS_INTERVAL_MS: '900000',
        FRESHNESS_XAUUSD_ONLY: 'true',
        FRESHNESS_STALE_LEAF_MIN: '30',
        FRESHNESS_STALE_DERIVED_MIN: '60',
        FRESHNESS_STALE_EVENT_MIN: '120',
        FRESHNESS_STALE_UNMANAGED_MIN: '360',
        FRESHNESS_AUTO_HEAL: 'false',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-freshness-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-freshness-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-freshness-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-feature-freshness-healer',
      script: 'C:\\tradzfx-v2\\scripts\\feature-freshness-monitor.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-feature-freshness-healer',
        TM_DB_POOL_MAX: '3',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '30000',
        EMA_CROSS_PAIRS: '9/21,50/200',
        SMA_CROSS_PAIRS: '50/200',
        FRESHNESS_INTERVAL_MS: '900000',
        FRESHNESS_XAUUSD_ONLY: 'true',
        FRESHNESS_STALE_LEAF_MIN: '30',
        FRESHNESS_STALE_DERIVED_MIN: '60',
        FRESHNESS_STALE_EVENT_MIN: '120',
        FRESHNESS_STALE_UNMANAGED_MIN: '360',
        FRESHNESS_AUTO_HEAL: 'true',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-freshness-healer-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-freshness-healer-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-freshness-healer-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    {
      name: 'tz-db-session-inventory',
      script: 'C:\\tradzfx-v2\\scripts\\db-session-inventory.js',
      cwd: 'C:\\tradzfx-v2',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradzfx_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: process.env.TM_DB_PASSWORD,
        TM_DB_APPLICATION_NAME: 'tradzfx-connection-audit',
        TM_DB_POOL_MAX: '1',
        TM_DB_CONNECTION_TIMEOUT: '5000',
        TM_DB_IDLE_TIMEOUT: '5000',
        TM_DB_SESSION_INVENTORY_INTERVAL_MS: '3600000',
        TM_DB_SESSION_INVENTORY_RETENTION_DAYS: '8',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-db-session-inventory-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-db-session-inventory-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-db-session-inventory-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
    // NOTE: tm-mt5-python-backfill is intentionally not managed by PM2 because
    // MetaTrader5's Python API must run in the same interactive Windows session
    // as the MT5 terminal (RDP session 3). It is started via
    // scripts/run-mt5-python-backfill.bat in that session.
  ],
};

for (const app of config.apps) {
  const roleUrlName = DB_ROLE_BY_PROCESS[app.name];
  if (!roleUrlName) continue;
  Object.assign(app.env, roleDbEnv(roleUrlName), { TM_DB_ROLE_URL_NAME: roleUrlName });
}

module.exports = config;
