module.exports = {
  apps: [
    {
      name: 'tm-web-v2',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3003',
      cwd: 'C:\\tradzfx-v2\\apps\\web',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        PORT: '3003',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradementor_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: '2k16Dub@i',
        TM_DB_POOL_MAX: '20',
        TM_DB_STATEMENT_TIMEOUT: '60000',
        TM_MT5_API_KEY: 'tm_mt5_93b214780ae6fdd83a726629535213b94e64bc3d4c0294ef',
        NINJA_LIVE_ENABLED: 'true',
        NINJA_LIVE_MODE: 'paper',
        NINJA_SYMBOLS: 'XAUUSD',
        NINJA_LOT_SIZE: '0.01',
        // Small-account safety guard: cap any risk-based lot calculation at 1 lot
        // and allow only one concurrent position total (and one per symbol).
        MAX_LOT_PER_ORDER: '1.0',
        SMALL_ACCOUNT_MAX_TOTAL: '1',
        SMALL_ACCOUNT_MAX_PER_SYMBOL: '1',
        SMALL_ACCOUNT_COOLDOWN_MINUTES: '30',
        SMALL_ACCOUNT_MAX_DAILY_LOSS_PCT: '5',
        NODE_OPTIONS: '--max-old-space-size=4096',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-web-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-web-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-web-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '5000M',
      kill_timeout: 5000,
      listen_timeout: 3000,
      shutdown_with_message: true,
      watch: false,
    },
    {
      name: 'tm-web-v2-ninja-trail',
      script: 'C:\\tradzfx-v2\\node_modules\\.bin\\tsx.cmd',
      args: 'scripts/run-ninja-trail-cron.ts',
      cwd: 'C:\\tradzfx-v2\\apps\\web',
      instances: 1,
      exec_mode: 'fork',
      interpreter: 'node',
      env: {
        NODE_ENV: 'production',
        TM_DB_HOST: 'localhost',
        TM_DB_PORT: '5432',
        TM_DB_NAME: 'tradementor_v2',
        TM_DB_USER: 'postgres',
        TM_DB_PASSWORD: '2k16Dub@i',
        TM_DB_POOL_MAX: '5',
        TM_MT5_API_KEY: 'tm_mt5_93b214780ae6fdd83a726629535213b94e64bc3d4c0294ef',
        NINJA_LIVE_ENABLED: 'true',
        NINJA_TRAIL_INTERVAL_MS: '10000',
      },
      error_file: 'C:\\tradzfx-v2\\logs\\pm2-ninja-trail-error.log',
      out_file: 'C:\\tradzfx-v2\\logs\\pm2-ninja-trail-out.log',
      log_file: 'C:\\tradzfx-v2\\logs\\pm2-ninja-trail-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      kill_timeout: 5000,
      watch: false,
    },
  ],
};
